title: Matthew Tole
email: matthew@matthewtole.com
description: The official website of Matthew Tole

baseurl: ""
url: "http://matthewtole.com"

twitter_username: matthewtole
github_username:  matthewtole

source: source/
destination: __public__/
plugins_dir: plugins/
