title: Matthew Tole
email: matthew@matthewtole.com
description: The official website of Matthew Tole

baseurl: "/matthewtole.com"
url: "https://matthewtole.github.io/matthewtole.com/"

twitter_username: matthewtole
github_username:  matthewtole
